/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "negate_test.check" instead.
 */

#include <check.h>
#include <stdint.h>
#include <stdio.h>

#include "../utils.h"

#define PATH "./test_cases/negate.bin"

#define NUMBER_OF_TESTS 50
#define DEC_PER_RECORD 2
#define SIZE_IN_BYTES 16
#define SIZE_IN_INTS 4
#define BUFFER_SIZE (DEC_PER_RECORD * NUMBER_OF_TESTS)
#define STEP (SIZE_IN_INTS * DEC_PER_RECORD)

FILE *file;
s21_decimal a;
s21_decimal res;
s21_decimal cs_res;
s21_decimal buffer[BUFFER_SIZE];

START_TEST(iterate) {
  memcpy(&a, buffer + _i * DEC_PER_RECORD, SIZE_IN_BYTES);
  memcpy(&cs_res, buffer + _i * DEC_PER_RECORD + 1, SIZE_IN_BYTES);
  s21_negate(a, &res);
  ck_assert_mem_eq(&res, &cs_res, SIZE_IN_BYTES);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("negate");
  TCase *tc1_1 = tcase_create("negate");
  SRunner *sr = srunner_create(s1);
  int nf;

  /* User-specified pre-run code */
  file = fopen(PATH, "rb");
  fread(buffer, BUFFER_SIZE, sizeof(s21_decimal), file);

  suite_add_tcase(s1, tc1_1);
  tcase_add_loop_test(tc1_1, iterate, 0, 50);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  /* User-specified post-run code */
  fclose(file);
}
